### ISSUE TITLE
RelatedObject deprecated ==> not compatible with Django 1.8

### ISSUE THREAD

**Issue by kskumar** [ramusus/django-twitter-api#11]
In `twitter_api.models`, this app references `django.db.models.related.RelatedObject`, which is deprecated as of Django 1.8 in favor of `django.db.models.fields.related.ForeignObjectRel` (see https://code.djangoproject.com/ticket/21414). As a result, an `ImportError` occurs ("no module named related").

How others have addressed it: https://github.com/treyhunner/django-simple-history/issues/156#issuecomment-91030594.

**Comment by ramusus** [comment]
https://github.com/ramusus/django-twitter-api/commit/ad1b42a9673aab293fa3bc8d9a8e2c8e8c2220d1

**Comment by kskumar** [comment]
Awesome! Will you be uploading this to PyPI?

**Comment by ramusus** [comment]
already uploaded

On Wed, Nov 18, 2015 at 7:47 PM, Sean <notifications@github.com> wrote:

> Awesome! Will you be uploading this to PyPI?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ramusus/django-twitter-api/issues/11#issuecomment-157774425>
> .
>



-- 
gtalk: *ramusus@gmail.com <ramusus@gmail.com>*
icq: 4543333
skype: ramusus
